version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    container_name: backend-${ENV} # 환경별 컨테이너 이름
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      POSTGRES_HOST: postgres  # 컨테이너명으로 지정
      POSTGRES_PORT: "5432"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis  # 컨테이너명으로 지정
      REDIS_PORT: "6379"
    depends_on:
      - redis
      - postgres
    restart: always
    networks:
      - backend-network

  redis:
    image: redis:latest
    container_name: redis-${ENV}
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend-network

  postgres:
    image: postgres:15
    container_name: postgres-${ENV}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
