spring:
  datasource:
    url: jdbc:postgresql://postgresql-development:5432/team1-db
    username: team1-master
    password: postgresql1234!
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
